### ISSUE TITLE
2024 Rust Annual Survey

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/leadership-council#105]
The survey team has prepared the next edition of the Rust Annual Survey. We're now looking for feedback before we freeze the questions (https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29).

I'm not sure if this information trickled down to all relevant teams. I also don't know if the teams care about it though. Anyway, seemed like something that could be interesting to the council. If not, feel free to ignore.

**Comment by apiraino** [comment]
The survey is out (🎉 ) so I think we close this :)

**Comment by ehuss** [comment]
Thanks! ❤
