### ISSUE TITLE
The HackMD workspace is not public

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/leadership-council#106]
### Question

The readme [claims](https://github.com/rust-lang/leadership-council?tab=readme-ov-file#hackmd) that the leadership council HackMD workspace is public. However, when I visit the [link](https://hackmd.io/team/rust-leadership-council), it just says "Forbidden". Perhaps it was not configured correctly?

**Comment by ehuss** [comment]
Sorry, will send a PR soon to fix the link. It should be https://hackmd.io/@rust-leadership-council for public viewing.
