### ISSUE TITLE
Grant proposals for 2024-2025

### ISSUE THREAD

**Issue by ehuss** [rust-lang/leadership-council#112]
I would like to direct a portion of the Council's budget to fund additional grants to Rust contributors. The budget for the [Fellowship Grants](https://foundation.rust-lang.org/news/announcing-the-rust-foundation-s-2024-fellows/) did not cover as many people as we would have liked.

We have four candidates that we would like to fund at $20,000 over 12 months as "Project Grants". This will come out of the $150,000 unreserved Council budget from 2024. We'll need to finalize the exact structure with the Foundation, but we are likely looking at it structured as an initial payment plus a mid-point payment contingent on how things are going (payments are unrestricted, no separate travel/hardware budget). This is also contingent on the candidates accepting the grants.

@Mark-Simulacrum and @jamesmunns and Paul Lenz have reviewed these candidates and agree that we would like to extend the grants to them.

I would like to ask the council to approve the proposed $80,000 for these grants.

Time: ~10 minutes

**Comment by ehuss** [comment]
@rfcbot fcp merge

Proposing to approve this.

**Comment by eholk** [comment]
Do we have a list of the four proposed grants somewhere?

**Comment by jamesmunns** [comment]
@eholk not public, as we haven't confirmed with the people whether they would like to accept. @ehuss can probably invite you to the doc shared with me and Mark

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
We discussed this in the last meeting.  People were on board with it, as reflected in the FCP, and that FCP has completed.
