### ISSUE TITLE
Approve changes to the COPYRIGHT notices shipped with Rust

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/leadership-council#120]
I have been working on updating how Rust reports the copyright notices and licenses for its various constituent parts as part of my work on Ferrocene (because we need to make the same reports).

The PR is https://github.com/rust-lang/rust/pull/133461

```quote
* Updates the `COPYRIGHT` file to describe how we actually do things now, and removes the licence text from it as they are stored elsewhere.
* dist tarballs get all of the files in `LICENSES/*`.
  * This folder is managed by `reuse` and each file exists because we refer to the licence somewhere in our tree. We should be supplying these licence texts to anyone who obtains a copy of the source code and now we do.
* The binary rust tarball gets `COPYRIGHT.html` and `COPYRIGHT-library.html`, which are auto-generated files that describe the licence information for both the in-tree source files used to build the Rust toolchain, and the out-of-tree dependencies we used to build the toolchain.
   * The other binary tarballs are unchanged, for now. In future you need to make a call whether to ship multiple version of COPYRIGHT.html, or whether to try and make, for example, a cargo-specific COPYRIGHT.html file.
* The `LICENSE-MIT` file now includes a blanket copyright statement, as the text indicates that it should and because users will expect to know who owns the copyright of the material they have been given (even if the answer is 'lots of people').
```

In other words, instead of the old COPYRIGHT file we will now ship all the reuse licenses and the new COPYRIGHT.html and COPYRIGHT-library.html files which are built by CI.

This is a non-trivial change because it:

* changes how the license for the Rust toolchain is expressed, and
* adds a 7MB HTML file to the binary distribution.

Asking infra to take a view on licensing matters seems slightly above their sign-off, and because this is a subject where People Have Strong Opinions and where being wrong can cost a lot of actual dollars, I wouldn't want it coming back on Infra for signing it off. I couldn't think of another team who have the appropriate sign-off authority here either.

So, I would like the Council to indicate to Infra whether would support the merging of this PR, or not. In preparing this PR I believe I am acting in accordance with the guidance supplied by the Rust Foundation and their legal team, but you shouldn't blindly trust me on that.

**Comment by jonathanpallant** [comment]
The use of REUSE is covered by this MCP: https://github.com/rust-lang/compiler-team/issues/519

Which has this tracking issue: https://github.com/rust-lang/rust/issues/99414

**Comment by traviscross** [comment]
See:

- https://github.com/rust-lang/rust/pull/133461#issuecomment-2523918248
- https://github.com/rust-lang/rust/pull/133461#issuecomment-2523955782

**Comment by ehuss** [comment]
We checked in with the legal counsel regarding the MIT license. They said that the copyright statement is optional, but still useful, and they agreed with the proposal here.

@rust-lang/leadership-council, I'd like to propose to merge https://github.com/rust-lang/rust/pull/133461. There is a link to a ZIP file at https://github.com/rust-lang/rust/pull/133461#issuecomment-2523918248 with what the new copyright files look like if you are interested in looking at them.

Since we don't have a process or clear owner or responsibility for this stuff, I'd like to just lean on the council to formally make a decision on this. Thus:

@rfcbot fcp merge

**Comment by traviscross** [comment]
@rfcbot reviewed

Looks right to me.
