### ISSUE TITLE
Substitute for 2025-01-14 Foundation board meeting

### ISSUE THREAD

**Issue by jamesmunns** [rust-lang/leadership-council#144]
We need to select a substitute for the 2025-01-14 Foundation board meeting place of @spastorino.

According to [our policy](https://github.com/rust-lang/leadership-council/blob/main/policies/project-directorship/board-meeting-substitutes.md), we need to make a public announcement (that's this issue) and agree by consensus to a substitute (also this issue).

cc @rust-lang/leadership-council

**Comment by jamesmunns** [comment]
@rfcbot fcp merge

I've checked availability, and am able to fill in on this date. Having recently arranged for the selection of project directors, I both have some useful context and am somewhat interested to join a meeting to build more, and will work with @spastorino in advance of the meeting to ensure that our key interests are represented in the same spirit as him being there, so if it pleases the council, I'm happy to fill in here.

**Comment by traviscross** [comment]
@rfcbot fcp merge
