### ISSUE TITLE
Figure out management of the team repo

### ISSUE THREAD

**Issue by ehuss** [rust-lang/leadership-council#35]
Currently the team repo is being managed by @rylev and @mark-simulacrum. Should this repo be managed by the Council? Should it be delegated to a distinct group? Should it be the infra team?

How do we handle private information (see https://github.com/rust-lang/core-team/issues/25)? Is this a responsibility of the Council, or the Infra team?

If the infra team doesn't have the capacity to help with development of new capabilities of the team system, what options do we have?

**Comment by Mark-Simulacrum** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/392734-council/topic/teams.20repo.20permissions (crosslinking that thread)

**Comment by ehuss** [comment]
https://github.com/rust-lang/rust-forge/pull/707 is open to resolve this.

**Comment by ehuss** [comment]
Closing as I think this effectively resolved by https://github.com/rust-lang/rust-forge/pull/707.
