### ISSUE TITLE
Figure out ownership and permissions of the forge

### ISSUE THREAD

**Issue by ehuss** [rust-lang/leadership-council#47]
https://forge.rust-lang.org/ is a central location for internal documentation of the Rust project. However, the permissions and management of the site do not seem clear to me, and I think it would be good to formalize and document that.

I don't know who actually has permissions right now to merge changes.

As a starting point, I'd like to propose allowing merge permissions for:
* Any teams that have a significant presence there (infra, release, council, docs.rs, crates.io, compiler, community, triagebot, lang, libs)
* Any team that wants to use the site as their home
* All team leads
* All project group leads

(The last two are just to mirror the "inside rust blog". I don't expect them to participate much.)

A branch protection should be in place to require a review from one maintainer.

I think a group should be delegated to be responsible for maintaining the site itself. That is, making sure its build process works, triaging and helping with issues, making sure PRs get attention when needed so they don't just sit, etc.

I'm not sure if it might be helpful to be clearer about guidelines for what content the site should contain. I don't think that has been an issue, but if there is a broader audience of people with merge permissions, it might help set up expectations.

**Comment by rylev** [comment]
The suggested permissions look good to me.

As for who maintains the site itself, t-infra seems appropriate. We'll probably want to start a discussion with them. 

Finally, as for what content should go in forge - this has been a long running discussion as some teams prefer to have documentation in team specific repos. As a first order move, I think we can have a policy that all documentation is *findable* from forge. That is, if a team wants their documentation to live somewhere else they should at least maintain links in forge to that documentation.
