### ISSUE TITLE
Establish the Edition 2024 Working Group

### ISSUE THREAD

**Issue by bstrie** [rust-lang/leadership-council#55]
In order to pursue the 2024 edition ([RFC](https://github.com/rust-lang/rfcs/pull/3501)), I hereby propose the creation of a working group with the following interested members joining as either active participants or observers:

@bstrie (team lead)
@ehuss (potential co-team lead)
@m-ou-se (potential co-team lead)
@estebank
@tmandry
@jhpratt 
@benwis
@me-diru
@scrabsha 

I request that the #edition-2021 Zulip stream be renamed to #edition to facilitate discussion for this edition and every future edition.

I anticipate no major procedural changes will need to be made in this edition cycle relative to prior editions. We will begin by asking the Rust project teams to nominate a list of of what features they would like to see in an edition, and then we may reject any of those if those are determined to be either infeasible to deliver in time for the edition (precise timeline TBD) or incompatible with the constraints of the edition mechanism.

Alternatively, it's possible that the Rust teams will conclude that it's not worth having an edition in 2024 (either due to a lack of potential features, or for any other reason). In that case, this working group will serve to determine such a conclusion.

**Comment by jhpratt** [comment]
I'd be interested in participating in this as well, if that's an option.

**Comment by bstrie** [comment]
Added. :)

**Comment by ehuss** [comment]
Closing, as this should now be resolved by https://github.com/rust-lang/team/pull/1105, and the Zulip stream should be set up.
