### ISSUE TITLE
Determine what to do with recording private meeting notes

### ISSUE THREAD

**Issue by ehuss** [rust-lang/leadership-council#60]
The council meetings sometimes cover [private topics](https://forge.rust-lang.org/governance/council.html#decisions-that-the-council-must-necessarily-make-privately). The council should probably figure out a policy for what to do with the notes in those situations. So far we have either:

* Temporarily omitted the notes until whatever needed to be made public was announced, and then later restore the missing content from the notes.
* Marked topics in the notes as "Private", but otherwise did not include them.
* Didn't mention the topic at all in the public notes.

I'm not sure what a good policy around this would be. Should there be some kind of private recording of these? Or should the notes just be lost in time?

Hopefully this should be rare, so I don't think this is too high of a priority. But if it continues to regularly happen, I think it would be good to figure this out.

**Comment by jonathanpallant** [comment]
I would prefer to see a set of private minutes, only available to those who were entitled to be in the meeting (being off sick is fine, you can see them, but joining the council a month later is not), and a set of redacted public minutes.

**Comment by carols10cents** [comment]
> only available to those who were entitled to be in the meeting (being off sick is fine, you can see them, but joining the council a month later is not),

Not sharing the history with new members sounds like a private GitHub repo is out.

Seems like the simplest thing is send them to current council members in an email?

**Comment by jonathanpallant** [comment]
That's a good idea.
