### ISSUE TITLE
Agenda item: sunsetting the Rust Wasm WG

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/leadership-council#84]
The Rust Wasm WG is part of the launching pad team, and has been effectively defunct for nearly five years now. It has no official members, and it's probably time we make it official that it's no longer active. I've filed an issue to make that change official here: https://github.com/rust-lang/team/pull/1489.

In https://github.com/rust-lang/team/pull/1489#issuecomment-2200286762 @rylev requested I file an issue with the council to discuss this in a meeting. I'd be more than happy to; I've been trying to get this in front of the council for nearly a year now, and I didn't realize I could file an issue here to put it on the council's agenda.

### Proposed process

Procedurally speaking, the process I intend to follow here is the same process we've followed for the Rust Async Ecosystem WG I co-lead and subsequently sunset. Once we decide to the shut the working group down:
1. We officially archive the working group in the `rust-lang/team` repo.
2. We offer project owners the ability to migrate projects from the `rustwasm` org to an org or account of their choosing.
3. We proceed to officially archive the `rustwasm` github org.

This ensures that any projects which are still useful or have activity have a life beyond the working group. But at the same time, this allows us to clearly communicate that these projects are now being developed outside of the Rust governance structure. Which is pretty just a way of codifying the way things have been for a while now.

**Comment by jamesmunns** [comment]
Closing this as completed as described in https://github.com/rust-lang/team/pull/1489#issuecomment-2203794452
