### ISSUE TITLE
A more stable travel grant policy

### ISSUE THREAD

**Issue by ehuss** [rust-lang/leadership-council#97]
The travel grant policy proposed in https://github.com/rust-lang/leadership-council/pull/96 says that it is "experimental". This issue is for tracking removing that "experimental" status.

I don't actually know what it would take to make that commitment, or what that even means. What would need to change to remove that paragraph?

Presumably any changes to that policy would still go through a consensus decision of the council whether it is experimental or not. Thus, perhaps we should just remove it now?

**Comment by traviscross** [comment]
I nominate this to consider the question that @ehuss raised above and whether we might be able to give feedback on it that would perhaps give the clarity needed for a concrete proposal to be written.

This might take five minutes.
